services:
  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_ADDON_DB}
      # Commented out due to configuration of only using root credentials on my local machine
      # MYSQL_USER: ${MYSQL_ADDON_USER}
      # MYSQL_PASSWORD: ${MYSQL_ADDON_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: